language: node_js
node_js:
  - 14.16.1
jdk:
  - oraclejdk8
addons:
  sonarcloud: true
script:
  - npm run cover
  - sonar-scanner -Dsonar.login=$SONAR_TOKEN -Dsonar.organization=manuelxp95 -Dsonar.projectKey=manuelxp95_integracioncontinua_v1  -Dsonar.sources='./app' -X
notifications:
  slack: 
    rooms: 
      - pruebademanu:E7NRp4JO3HuhRWuGqoEhl56s#random
    template:
      - "CHOQUE LA MOTO... PERO GRACIAS A CRISTO A REY NO ME PASO NADA 😎"