language: node_js
node_js:
  - 14.16.1
jdk:
  - oraclejdk8
addons:
  sonarcloud: true
script:
  - sonar-scanner -Dsonar.login=SONAR_TOKEN -Dsonar.organization=manuelxp95 -Dsonar.projectKey=manuelxp95_integracioncontinua_v1 -Dsonar.sources='./app' -X