language: node_js
node_js:
  - 14.16.1
jdk:
  - oraclejdk8
addons:
  sonarcloud:
  organization: "manuelxp95"
  token:
    secure: "31fe127f15a4996275e2cfb2c1da756071f2b29f" # encrypted value of your token
script:
  - sonar-scanner
